version: 2.1
jobs:
  build_book:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: setup environment
          command: |
            pip install -r requirements.txt
            pip list
      - run:
          name: Build Site Markdown
          command: jupyter-book build .

      - store_artifacts:
          path: _build/html
          destination: html


# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  build_book:
    jobs:
      - build_book
